*PADS-LIBRARY-PART-TYPES-V9*

INDM4040X180N INDM4040X180N M IND 4 0 0 0 0
"Geometry.Height" 1.8mm
"Description" Inductor,Molded Body;4.00mm L X 4.00mm W X 1.80mm H
"Standard Name"
"Manufacturer"

*END*
*REMARK* Generated by PADS Land Pattern Creator VX.2.7
