*PADS-LIBRARY-PART-TYPES-V9*

LEDC3216X110N_REVERSE_MOUNT LEDC3216X110N_REVERSE_MOUNT M LED 2 0 0 2 0
"Geometry.Height" 1.1mm
"Description" LED,Chip;3.20mm L X 1.60mm W X 1.10mm H Reverse Mount
C A 

*END*
*REMARK* Generated by PADS Land Pattern Creator VX.2.7
