*PADS-LIBRARY-PART-TYPES-V9*

PAD310P_AWG8 PAD310P_AWG8 M PAD 7 0 0 0 0
"Description" Wire,10 guage;3.10mm diameter
"Standard Name"
"Manufacturer"
"Mfr Package Name"
"Mfr Package Code"
"Mfr Package Description"
"On-Line-Link"

*END*
*REMARK* Generated by PADS Land Pattern Creator VX.2.3
