*PADS-LIBRARY-PART-TYPES-V9*

SOIC127P790X216-8N SOIC127P790X216-8N M SOI 4 0 0 0 0
"Geometry.Height" 2.16mm
"Description" SOIC,1.27mm pitch;8 pin,5.28mm W X 5.28mm L X 2.16mm H body
"Standard Name" soic-8-208-mil
"Manufacturer"

*END*
*REMARK* Generated by PADS Land Pattern Creator VX.2.7
