*PADS-LIBRARY-PART-TYPES-V9*

SOIC127P600X175-8N SOIC127P600X175-8N M SOI 4 0 0 0 0
"Geometry.Height" 1.75mm
"Description" SOIC,1.27mm pitch;8 pin,3.90mm W X 4.90mm L X 1.75mm H body
"Standard Name" soic-8-208-mil
"Manufacturer"

*END*
*REMARK* Generated by PADS Land Pattern Creator VX.2.7
